In [1]:
from keras.models import load_model
model = load_model('faces_VGG16.h5')

Using TensorFlow backend.


In [2]:
import cv2
import numpy as np
cap = cv2.VideoCapture(0 , cv2.CAP_DSHOW)
while True :
    status , photo = cap.read()
    face_model = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
    face_cor = face_model.detectMultiScale(photo)
    if len(face_cor) != 0:
        x , y , h , w = face_cor[0]
        cv2.rectangle(photo , (x,y) , (x+w,y+h) , (0,255,0) , 2 )
        crop_photo = photo[y:y+h , x:x+w]
        crop_resize = cv2.resize(crop_photo,(224,224))
        face = np.expand_dims(crop_resize,axis=0)
        prediction = model.predict(face)
        print(prediction)
        #cv2.putText(photo , str(prediction), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        
        if prediction[0][0] == max(prediction[0]) :
            cv2.putText(photo, "Hey ASHISH", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            #cv2.imshow('Face Recognition', photo )
            
        elif prediction[0][1] == max(prediction[0]) :
            cv2.putText(photo, "Hey POORVI", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            #cv2.imshow('Face Recognition', photo )
            
        elif prediction[0][2] == max(prediction[0]) :
            cv2.putText(photo, "Hey PUSHPA", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            #cv2.imshow('Face Recognition', photo )
            
        elif prediction[0][3] == max(prediction[0]) :
            cv2.putText(photo, "Hey SHOBHA", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            #cv2.imshow('Face Recognition', photo )
            
    cv2.imshow('face' , photo)
    if cv2.waitKey(1) == 13 :
        break
cap.release()
cv2.destroyAllWindows()

[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.1954986e-09]]
[[0.000000e+00 9.999410e-01 0.000000e+00 5.895512e-05]]
[[0. 0. 0. 1.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[0.000000e+00 5.326931e-30 0.000000e+00 1.000000e+00]]
[[0. 1. 0. 0.]]
[[1. 0. 0. 0.]]
[[9.999993e-01 5.779332e-28 0.000000e+00 6.789628e-07]]
[[1.0000000e+00 1.4706099e-15 0.0000000e+00 0.0000000e+00]]
[[1.000000e+00 9.044725e-17 0.000000e+00 0.000000e+00]]
[[0. 1. 0. 0.]]
[[2.410187e-36 1.000000e+00 0.000000e+00 0.000000e+00]]
[[0. 1. 0. 0.]]
[[8.122872e-17 1.000000e+00 0.000000e+00 0.000000e+00]]
[[0. 1. 0. 0.]]
[[0. 1. 0. 0.]]
[[1.8100422e-29 1.0000000e+00 0.0000000e+00 2.1473486e-20]]
[[9.9999964e-01 2.1501493e-22 0.0000000e+00 3.4049137e-07]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[1. 0. 0. 0.]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 1.3770578e-13]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 7.5839475e-18]]
[[0.0000000e+00 1.0000000e+00 0.0000000e+00 9.9829576e-17]]
[[1.0000000e+00 0.00